### ISSUE TITLE
mkv excerpt file not written

### ISSUE THREAD

**Issue by fyocouch** [lvml/mpv-plugin-excerpt#2] opened 2015-08-10 00:56 UTC
Warning: option --lua-opts was replaced with --script-opts and might be removed in the future.
[excerpt] begin=0.000s end=0.000s duration= 0.000s  
begin=0.000s end=0.000s duration= 0.000s 
Playing: Modern Slavery More Black Males in Prison Today Than Enslaved in 1850-H0SGvJEfgh4.mp4
 (+) Video --vid=1 (_) (h264)
 (+) Audio --aid=1 --alang=und (_) (aac)

AO: [pulse] 44100Hz stereo 2ch float
VO: [opengl] 426x240 yuv420p
AV: 00:00:04 / 00:04:10 (1%) A-V:  0.000
[excerpt] begin=0.000s end=4.178s duration= 4.178s  
AV: 00:00:07 / 00:04:10 (3%) A-V:  0.000
[excerpt] begin=7.921s end=7.921s duration= 0.000s  
AV: 00:00:11 / 00:04:10 (4%) A-V:  0.000
[excerpt] begin=11.765s end=11.765s duration= 0.000s  
AV: 00:00:17 / 00:04:10 (7%) A-V:  0.000
[excerpt] begin=17.814s end=17.814s duration= 0.000s  
AV: 00:00:23 / 00:04:10 (9%) A-V:  0.000
[excerpt] begin=17.814s end=23.095s duration= 5.281s  
AV: 00:00:24 / 00:04:10 (9%) A-V:  0.000
[excerpt] begin=17.814s end=23.095s duration= 5.281s writing excerpt of source file 'Modern Slavery More Black Males in Prison Today Than Enslaved in 1850-H0SGvJEfgh4.mp4'
[excerpt] to destination file 'excerpt_000.mkv' 
AV: 00:00:24 / 00:04:10 (9%) A-V:  0.000
Running subprocess failed: init
AV: 00:00:43 / 00:04:10 (17%) A-V:  0.000

 mpv --version
mpv 0.9.2 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
libav library versions:
   libavutil       54.3.0
   libavcodec      56.1.0
   libavformat     56.1.0
   libswscale      3.0.0
   libavfilter     5.0.0
   libavresample   2.1.0

After pressing "x", it says that it is writing the excerpt file out. But I can not find the excerpt file out....
Am I missing something?

**Comment by lvml** [comment] 2015-08-11 18:33
`Running subprocess failed: init` seems to be the only hint into what is going wrong - at this point, excerpt.lua is probably executing

```
mp.commandv("run", "excerpt_copy", excerpt_begin, duration, srcname, fname)
```

to run the "excerpt_copy" batch script.

Are you running this under Windows? If yes, then possibly your issue is the same as: https://github.com/mpv-player/mpv/issues/1908

If you are running this under Unix, are you sure the excerpt_copy script is in your $PATH?

**Comment by lvml** [comment] 2015-10-25 00:47
Today's commit also includes a better reporting of error conditions when trying to invoke excerpt_copy.

BTW: With an much-older-than-current mpv version, I found one reason for the `Running subprocess failed: init` issue: mpv "leaked threads", creating additional threads whenever the next file was opened, and after 30 or so it would not open any more threads. Under Linux, you could check for this with a command like `ps -eLf | grep mpv | wc -l`, looking at the number of threads, whether it changes when you advance to the next file.

But that "mpv leaking threads" issue must have been fixed at some time - with a current mpv version, I cannot reproduce this.

Closing this issue.

**Closed as completed by lvml** 2015-10-25 00:47 UTC
